// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// new_classy1
SEXP new_classy1(std::vector< double > x_);
RcppExport SEXP _classy_new_classy1(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector< double > >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(new_classy1(x_));
    return rcpp_result_gen;
END_RCPP
}
// classy_get1
SEXP classy_get1(SEXP p_);
RcppExport SEXP _classy_classy_get1(SEXP p_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    rcpp_result_gen = Rcpp::wrap(classy_get1(p_));
    return rcpp_result_gen;
END_RCPP
}
// classy_count1
int classy_count1(SEXP p_);
RcppExport SEXP _classy_classy_count1(SEXP p_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    rcpp_result_gen = Rcpp::wrap(classy_count1(p_));
    return rcpp_result_gen;
END_RCPP
}
// classy_sum1
double classy_sum1(SEXP p_);
RcppExport SEXP _classy_classy_sum1(SEXP p_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    rcpp_result_gen = Rcpp::wrap(classy_sum1(p_));
    return rcpp_result_gen;
END_RCPP
}
// classy_count_if_less1
double classy_count_if_less1(SEXP p_, double y);
RcppExport SEXP _classy_classy_count_if_less1(SEXP p_SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(classy_count_if_less1(p_, y));
    return rcpp_result_gen;
END_RCPP
}
// new_classy3
SEXP new_classy3(NumericVector x_);
RcppExport SEXP _classy_new_classy3(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(new_classy3(x_));
    return rcpp_result_gen;
END_RCPP
}
// classy_get3
SEXP classy_get3(SEXP p_);
RcppExport SEXP _classy_classy_get3(SEXP p_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    rcpp_result_gen = Rcpp::wrap(classy_get3(p_));
    return rcpp_result_gen;
END_RCPP
}
// classy_count3
int classy_count3(SEXP p_);
RcppExport SEXP _classy_classy_count3(SEXP p_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    rcpp_result_gen = Rcpp::wrap(classy_count3(p_));
    return rcpp_result_gen;
END_RCPP
}
// classy_sum3
double classy_sum3(SEXP p_);
RcppExport SEXP _classy_classy_sum3(SEXP p_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    rcpp_result_gen = Rcpp::wrap(classy_sum3(p_));
    return rcpp_result_gen;
END_RCPP
}
// classy_count_if_less3
double classy_count_if_less3(SEXP p_, double y);
RcppExport SEXP _classy_classy_count_if_less3(SEXP p_SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p_(p_SEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(classy_count_if_less3(p_, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_classy_new_classy1", (DL_FUNC) &_classy_new_classy1, 1},
    {"_classy_classy_get1", (DL_FUNC) &_classy_classy_get1, 1},
    {"_classy_classy_count1", (DL_FUNC) &_classy_classy_count1, 1},
    {"_classy_classy_sum1", (DL_FUNC) &_classy_classy_sum1, 1},
    {"_classy_classy_count_if_less1", (DL_FUNC) &_classy_classy_count_if_less1, 2},
    {"_classy_new_classy3", (DL_FUNC) &_classy_new_classy3, 1},
    {"_classy_classy_get3", (DL_FUNC) &_classy_classy_get3, 1},
    {"_classy_classy_count3", (DL_FUNC) &_classy_classy_count3, 1},
    {"_classy_classy_sum3", (DL_FUNC) &_classy_classy_sum3, 1},
    {"_classy_classy_count_if_less3", (DL_FUNC) &_classy_classy_count_if_less3, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_classy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
