# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The `classy1` C++ class (copies R objects)
#' @param x A numeric vector.
#' @param p A pointer to a classy1 object.
#' @param y Numeric scalar.
#' @return
#' The `new_classy1` function creates an object of C++ class `classy`. This is
#' an object of class [externalptr-class] in the R side.
#'
#' `classy_sum1` and `classy_count` return the sum and the count of elements
#' in the `x` vector passed to `new_classy`.
#'
#' `classy_count_if1` returns the count of elements in `x` if these are less
#' than `y`.
#'
#' `classy_get1` returns the original vector `x` passed to `new_classy`.
#' @export
#' @name classy1-class
#' @examples
#'
#' # Creating a new object
#' set.seed(1)
#' obj <- new_classy1(runif(10))
#'
#' # Getting the sum
#' classy_sum1(obj)
#'
#' # Counting
#' classy_count1(obj)
#'
#' # Conditional count
#' classy_count_if_less1(obj, 0.5)
#'
#' # The object
#' classy_get1(obj)
#'
#' # Removing
#' rm(obj)
#'
#' # If we call the garbage collector, you can see the destructor been called
#' gc()
new_classy1 <- function(x) {
    .Call(`_classy_new_classy1`, x)
}

#' @export
#' @rdname classy1-class
classy_get1 <- function(p) {
    .Call(`_classy_classy_get1`, p)
}

#' @export
#' @rdname classy1-class
classy_count1 <- function(p) {
    .Call(`_classy_classy_count1`, p)
}

#' @export
#' @rdname classy1-class
classy_sum1 <- function(p) {
    .Call(`_classy_classy_sum1`, p)
}

#' @export
#' @rdname classy1-class
classy_count_if_less1 <- function(p, y) {
    .Call(`_classy_classy_count_if_less1`, p, y)
}

#' @export
#' @rdname classy1-class
classy_get_address1 <- function(p) {
    invisible(.Call(`_classy_classy_get_address1`, p))
}

#' The `classy3` C++ class (uses smart pointers)
#' @param x A numeric vector.
#' @param p A pointer to a classy3 object.
#' @param y Numeric scalar.
#' @return
#' The `new_classy3` function creates an object of C++ class `classy3`. This is
#' an object of class [externalptr-class] in the R side.
#'
#' `classy_sum3` and `classy_count3` return the sum and the count of elements
#' in the `x` vector passed to `new_classy`.
#'
#' `classy_count_if3` returns the count of elements in `x` if these are less
#' than `y`.
#'
#' `classy_get3` returns the original vector `x` passed to `new_classy`.
#' @export
#' @name classy3-class
#' @examples
#'
#' # Creating a new object
#' set.seed(1)
#' obj <- new_classy3(runif(10))
#'
#' # Getting the sum
#' classy_sum3(obj)
#'
#' # Counting
#' classy_count3(obj)
#'
#' # Conditional count
#' classy_count_if_less3(obj, 0.5)
#'
#' # The object
#' classy_get3(obj)
#'
#' # Removing
#' rm(obj)
#'
#' # If we call the garbage collector, you can see the destructor been called
#' gc()
new_classy3 <- function(x) {
    .Call(`_classy_new_classy3`, x)
}

#' @export
#' @rdname classy3-class
classy_get3 <- function(p) {
    .Call(`_classy_classy_get3`, p)
}

#' @export
#' @rdname classy3-class
classy_count3 <- function(p) {
    .Call(`_classy_classy_count3`, p)
}

#' @export
#' @rdname classy3-class
classy_sum3 <- function(p) {
    .Call(`_classy_classy_sum3`, p)
}

#' @export
#' @rdname classy3-class
classy_count_if_less3 <- function(p, y) {
    .Call(`_classy_classy_count_if_less3`, p, y)
}

#' @export
#' @rdname classy3-class
classy_get_address3 <- function(p) {
    invisible(.Call(`_classy_classy_get_address3`, p))
}

#' Get the address of an R vector
#' @param x A numeric vector.
#' @export
get_address <- function(x) {
    invisible(.Call(`_classy_get_address`, x))
}

