# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The `classy` C++ class
#' @param x A numeric vector.
#' @return
#' The `new_classy` function creates an object of C++ class `classy`. This is
#' an object of class [externalptr-class] in the R side.
#'
#' `classy_sum` and `classy_count` return the sum and the count of elements
#' in the `x` vector passed to `new_classy`.
#'
#' `classy_count_if` returns the count of elements in `x` if these are less
#' than `y`.
#'
#' `classy_get` returns the original vector `x` passed to `new_classy`.
#' @export
#' @aliases classy classy-class
#' @examples
#'
#' # Creating a new object
#' set.seed(1)
#' obj <- new_classy(runif(10))
#'
#' # Getting the sum
#' classy_sum(obj)
#'
#' # Counting
#' classy_count(obj)
#'
#' # Conditional count
#' classy_count_if_less(obj, 0.5)
#'
#' # The object
#' classy_get(obj)
#'
#' # Removing
#' rm(obj)
#'
#' # If we call the garbage collector, you can see the destructor been called
#' gc()
new_classy <- function(x_) {
    .Call(`_classy_new_classy`, x_)
}

#' @export
#' @rdname new_classy
classy_get <- function(p_) {
    .Call(`_classy_classy_get`, p_)
}

#' @export
#' @rdname new_classy
classy_count <- function(p_) {
    .Call(`_classy_classy_count`, p_)
}

#' @export
#' @rdname new_classy
classy_sum <- function(p_) {
    .Call(`_classy_classy_sum`, p_)
}

#' @export
#' @rdname new_classy
classy_count_if_less <- function(p_, y) {
    .Call(`_classy_classy_count_if_less`, p_, y)
}

